import { useCallback, useEffect, useState } from 'react';
import Button from '../components/Button.jsx';
import Card from '../components/Card.jsx';
import Table from '../components/Table.jsx';
import Toast from '../components/Toast.jsx';
import { API_BASE, useAuth } from '../context/AuthContext.jsx';

export default function ManagerDutyAssignment() {
  const { token } = useAuth(); const [residents, setResidents] = useState([]); const [duties, setDuties] = useState([]); const [form, setForm] = useState({ residentId: '', type: 'bazar', date: '' }); const [toast, setToast] = useState(null);
  const api = useCallback(async (path, options = {}) => { const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...options.headers } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Request failed'); return result.data; }, [token]);
  const load = useCallback(async () => { try { const [residentData, dutyData] = await Promise.all([api('/duty/residents'), api('/duty')]); setResidents(residentData); setDuties(dutyData); } catch (error) { setToast({ message: error.message, variant: 'error' }); } }, [api]);
  useEffect(() => { load(); }, [load]);
  const submit = async (event) => { event.preventDefault(); try { await api('/duty', { method: 'POST', body: JSON.stringify(form) }); setForm({ residentId: '', type: 'bazar', date: '' }); setToast({ message: 'Duty assigned.', variant: 'success' }); load(); } catch (error) { setToast({ message: error.message, variant: 'error' }); } };
  const cancel = async (id) => { try { await api(`/duty/${id}`, { method: 'PATCH', body: JSON.stringify({ status: 'cancelled' }) }); setToast({ message: 'Duty assignment cancelled.', variant: 'success' }); load(); } catch (error) { setToast({ message: error.message, variant: 'error' }); } };
  const columns = [{ key: 'resident', header: 'Resident', render: (duty) => duty.residentId?.userId?.name ?? 'Resident' }, { key: 'type', header: 'Duty', render: (duty) => duty.type }, { key: 'date', header: 'Date', render: (duty) => new Date(duty.date).toLocaleDateString() }, { key: 'status', header: 'Status' }, { key: 'action', header: '', render: (duty) => duty.status === 'assigned' && <Button size="sm" variant="secondary" onClick={() => cancel(duty._id)}>Cancel</Button> }];
  return <><Card className="mb-5" header="Assign a duty"><form className="grid gap-3 md:grid-cols-4" onSubmit={submit}><select required value={form.residentId} onChange={(event) => setForm({ ...form, residentId: event.target.value })} className="rounded-control border border-sky300 bg-white px-3 py-2.5 text-darkText"><option value="">Select a resident</option>{residents.map((resident) => <option key={resident._id} value={resident._id}>{resident.userId?.name}</option>)}</select><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="rounded-control border border-sky300 bg-white px-3 py-2.5 text-darkText"><option value="bazar">Bazar</option><option value="cleaning">Cleaning</option><option value="washroom">Washroom</option></select><input required type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} className="rounded-control border border-sky300 bg-white px-3 py-2.5 text-darkText" /><Button type="submit">Assign</Button></form></Card><Card header="Duty assignments"><Table columns={columns} data={duties} /></Card><Toast {...toast} onDismiss={() => setToast(null)} /></>;
}
